### ISSUE TITLE
Problem with nette/http:2.4.10

### ISSUE THREAD

**Issue by JohnyRicio** [Kdyby/FakeSession#11]
Hi.
when you update nette/http to version 2.4.10, you will see error:
Declaration of Kdyby\FakeSession\Session::setCookieParameters($path, $domain = NULL, $secure = NULL) should be compatible with Nette\Http\Session::setCookieParameters($path, $domain = NULL, $secure = NULL, $samesite = NULL)

at nette/http version 2.4.10 was added 4th parametrs sameSite.

Many thanx for fix it.

**Comment by xificurk** [comment]
This is resolved, 2.0.1 has already benn published to packagist some time ago.
